#!/bin/bash
myPath=$(eval "pwd")
scriptPath=$(dirname $(readlink -f $0))

if [ -z "$1"]
	then
		message="default commit message"
		echo "fucker didn't change the $message"
	else
		message=$1
fi



cd $scriptPath
git add *
git commit -m "$message"
git push origin master
cd $myPath
