#!/bin/bash
myPath=$(eval "pwd")
scriptPath=$(dirname $(readlink -f $0))

if [ -z "$1"]
	then
		message="default commit message"
	else
		message=$1
fi

echo " fucker $message"

cd $scriptPath
git add *
git commit -m "fucker $message"
git push origin master
cd $myPath
