#!/bin/bash
myPath=$(eval "pwd")
scriptPath=$(dirname $(readlink -f $0))
message=$1

echo " fucker $message"

cd $scriptPath
git checkout -b ohgodwhy
git add *
git commit -m "$message"
git push origin ohgodwhy
cd $myPath
